### ISSUE TITLE
Experience section does not align vertically

### ISSUE THREAD

**Issue by bstein** [BlackrockDigital/startbootstrap-resume#107]
Unlike the other sections, the experience section is not vertically centered. Note that you have to reduce the amount of content to notice this effect.

On like 92...

`<section class="resume-section p-3 p-lg-5 d-flex justify-content-center" id="experience">`

... I think including justify-content-center was a mistake. It should be align-items-center, like the other sections...

`<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="experience">`

**Comment by davidtmiller** [comment]
Updated as of most recent build.
