### ISSUE TITLE
Navbar Image Height

### ISSUE THREAD

**Issue by brian-regan** [BlackrockDigital/startbootstrap-resume#12]
![image](https://user-images.githubusercontent.com/24444009/36075063-3ca483b8-0f49-11e8-8070-3c3adb6948c5.png)

I'm getting a strange error when I upload the files to a server. Locally, everything looks fine but when I upload it the height of the `<a class="navbar-brand js-scroll-trigger" href="#page-top">` is incorrect.

**Comment by SamwiseGambgee** [comment]
@brian-regan, how did you change the color of nav, hover ?

**Comment by davidtmiller** [comment]
It looks like the flexbox positioning is messing up somewhere along the line...did you get this fixed?
