### ISSUE TITLE
Deploy the Project to Server

### ISSUE THREAD

**Issue by namioz** [BlackrockDigital/startbootstrap-resume#137]
Hello,
I am trying to Deploy this project to server,
but after i install the pm2 i try to run this command:

> pm2 start node_modules/.bin/gulp

```
    "scripts": {
        "start": "node_modules/.bin/gulp watch"
    },
```

but i dont success to deploy this
when i try to do 
 

> npm start 

 it is work locally ,
what the problem??

**Comment by davidtmiller** [comment]
Gulp has been deprecated, this was replaced with npm scripts.
