### ISSUE TITLE
Upgrade to FontAwesome 4->5

### ISSUE THREAD

**Issue by SITZ** [BlackrockDigital/startbootstrap-resume#15]
Seems like [FontAwesome](https://github.com/FortAwesome/Font-Awesome) is going to deprecate versions 3 & 4 soon and lots of new icons and features have been added to version 5.
I used this theme today and migrated the personal version to 5. Would you guys want to to this migration or accepting any pull requests in that regard?

**Comment by tiagoanleite** [comment]
I've done a very simple PR with the newer Font Awesome icon set. Let's see if it gets merged into the project.

Keep in mind that I used the shim in order to avoid messing any potencial CSS customizations made for FA4. Updating the templates to use the newer FA5 calls would be the best approach.

**Comment by davidtmiller** [comment]
Done in the last update, thanks!
