### ISSUE TITLE
Close unhelpful pull requests

### ISSUE THREAD

**Issue by ChrisLane** [BlackrockDigital/startbootstrap-resume#183]
A lot of people seem to think that this repo should pull in their personal resume changes to the project.

The number of pull requests for changes that should never be pulled into the repo (e.g. #180) makes it harder to see changes that should actually be reviewed and possibly merged (e.g. #111, #175).
It would be helpful if pull requests could be reviewed and closed if they don't provide anything of value to the project.

**Comment by davidtmiller** [comment]
Done!
