### ISSUE TITLE
Recreate resume template using vue

### ISSUE THREAD

**Issue by raihan71** [BlackrockDigital/startbootstrap-resume#190]
hi there, can I just recreate this template using vue and published to my github?

**Comment by aneta-s** [comment]
Same question for React 🥇

**Comment by raihan71** [comment]
> Same question to recreate it in React 🥇 would be awesome!

woah haha it is cool

**Comment by raihan71** [comment]
actually, I already have done it recreated to vue called VuePorto 😄 checkout my github

**Comment by aneta-s** [comment]
I’ve just seen that! It looks nice indeed. Any tutorial recommendation how to recreate a website in newer libraries ie React😊

**Comment by raihan71** [comment]
> I’ve just seen that! It looks nice indeed. Any tutorial recommendation how to recreate a website in newer libraries ie React😊

you can check from Brad Traversy 👍

**Comment by aneta-s** [comment]
Aight! Thank you for sharing this info, good luck with your website. Really nice one!

**Comment by raihan71** [comment]
> Aight! Thank you for sharing this info, good luck with your website. Really nice one!

thanks! hey, let's follow each other then
