### ISSUE TITLE
hoek security vulnerability

### ISSUE THREAD

**Issue by ToonWeyens** [BlackrockDigital/startbootstrap-resume#23]
A dependency defined in ./package-lock.json has known security vulnerabilities and should be updated.

Is this an easy one to fix?

**Comment by bertrandgorge** [comment]
Maybe there: https://forums.meteor.com/t/solved-email-from-github-security-vulnerability-in-package-lock-json/43422/4

**Comment by ToonWeyens** [comment]
Thanks I managed :-)
