### ISSUE TITLE
why profile pic is not showing in mobile browsers

### ISSUE THREAD

**Issue by rk1809** [BlackrockDigital/startbootstrap-resume#33]
Hi, 
Thanks for the awesome template. 
I modified and hosted the template, which looks good in desktop and also in mobile, but profile pic is missing in mobile browsers. 
Is it designed that way or am I missing something?.

**Comment by kavierkoo** [comment]
I thinks its by design, 
Anyway, if you wanted to show your profile picture on mobile, 
simply remove the **`d-none`** from your code for image.

Instead of:
```
<span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle ">
</span>
```

This works for me on mobile browser:
```
<span class="d-lg-block">
          <img class="img-fluid img-profile rounded-circle ">
</span>
```

**Comment by narbhar** [comment]
If you remove the "d-none" tag it seems to display only the profile image in mobile view

**Comment by kavierkoo** [comment]
I see what you meant.. after removing the "d-none" it looks huge, 
even after I tried to resize the image by changing the width and height
```
<span class="d-lg-block">
    <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="xxxx" height="100px" width="100px:>
</span>
```
anyway if you want to only change the mobile view, you can try responsive css. 

```
@media only screen and (max-width:500px) {
  /* For mobile */

}
```

but it still looks weird as it falls under navbar.

**Comment by davidtmiller** [comment]
This is a feature of the theme. You could certainly add it back in at another part of the page by using Bootstrap's responsive display utilities, but as it stands the profile picture will disappear on mobile since it's included as part of the navigation.
