### ISSUE TITLE
Social Media Icons are not working. 

### ISSUE THREAD

**Issue by am934743** [BlackrockDigital/startbootstrap-resume#34]
Hello - there is a conflicting CSS file overwriting some styles that prevent the icons from being displayed. 

The demo you have reflects this as well.

**Comment by X-hung** [comment]
for temporary use, just modify the class name of <div class="social-icons"> in HTML file, here I used social-iconss, then it works.

**Comment by X-hung** [comment]
> Hello - there is a conflicting CSS file overwriting some styles that prevent the icons from being displayed.
> 
> The demo you have reflects this as well.

for temporary use, just modify the class name of

in HTML file, here I used social-iconss, then it works.

**Comment by X-hung** [comment]
> Hello - there is a conflicting CSS file overwriting some styles that prevent the icons from being displayed.
> 
> The demo you have reflects this as well.

for temporary use, just modify the class name of <div class="social-iconss"> in HTML file, here I used social-iconss, then it works.

**Comment by X-hung** [comment]
> Hello - there is a conflicting CSS file overwriting some styles that prevent the icons from being displayed.
> 
> The demo you have reflects this as well.

for temporary use, just modify the class name of " div class="social-icons" "

in HTML file, here I used "social-iconss", then it works.

**Comment by davidtmiller** [comment]
The social icons should be working now!
