### ISSUE TITLE
You can add a block Projects?

### ISSUE THREAD

**Issue by yarkovaleksei** [BlackrockDigital/startbootstrap-resume#60]
You can add a block Projects, where will be listed some projects that are not ashamed to show?

**Comment by avipars** [comment]
It's relatively easy to add yourself. Just look at the menu and then add another option: 
   <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#projects">Projects</a>
        </li>
Afterward, copy the code of another section and then change the anchor and title to projects. Now you have a project section. Here is the difficult part. If you want to format differently or add an image next to your project, you'll need to play around with html.
