### ISSUE TITLE
untrusted SSL

### ISSUE THREAD

**Issue by radiohalo5** [BlackrockDigital/startbootstrap-resume#8]
When running "npm i startbootstrap-resume"

I get this message

npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:440:26)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient (http.js:1256:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:91:29)
npm ERR!     at CleartextStream.socketOnData (http.js:1288:20)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR!     at EncryptedStream.write (tls.js:130:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!  [Error: SSL Error: CERT_UNTRUSTED]

Time to update your cert?

**Comment by davidtmiller** [comment]
I'm not getting any errors on this end, I am not sure this is related to the theme or package itself.

**Comment by radiohalo5** [comment]
Not sure how this works. Should i open an issue with someone else?  I could download it from here, but I thought you should know.
