### ISSUE TITLE
Navbar won't collapse when clicking on hamburger menu

### ISSUE THREAD

**Issue by mintkey** [BlackrockDigital/startbootstrap-resume#84]
Not sure if this is the right place to put this, but I haven't found a solution on similar topics to this. I guess this is by design, but the hamburger menu on the smaller layout doesn't collapse unless you click/tap on a menu item, but I'd like to be able to collapse it by clicking/tapping on the hamburger menu again. Is there any way I can do this? (I don't have enough web dev experience to figure it out myself.) Thanks in advance!

**Comment by kavierkoo** [comment]
Hi, I think I managed to find the issue of your code,

after analyzing with Chrome's  "developer tools" > "Event Listeners" > "Click" > remove the "jquery-3.3.1.slim.min.js"

your site's hamburger menu icon seems working again.

As "Collapse" function from bootstrap require jquery to work,  "jquery-3.3.1.slim.min.js" seems conflicted with "collapse.js" inside the bundle of "bootstrap.bundle.min.js".

Hope this helps!

**Comment by mintkey** [comment]
Yes, that fixed my issue!! Thanks so much!
